
//! Autogenerated weights for `pallet_sponsored_tx`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Mac.lan`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/parachain-template-node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution
// compiled
// --pallet
// pallet_sponsored_tx
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/sponsored-tx/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame::{
	deps::frame_support::{traits::Get, weights::constants::RocksDbWeight},
	prelude::*,
};

/// Weight functions for `pallet-sponsored-tx`.
pub trait WeightInfo {
	fn register_sponsor(n: u32) -> Weight;
	fn increase_budget() -> Weight;
	fn decrease_budget() -> Weight;
	fn set_policy(n: u32) -> Weight;
	fn pause() -> Weight;
	fn resume() -> Weight;
	fn unregister() -> Weight;
}

/// Weights for `pallet_sponsored_tx` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn register_sponsor(n: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `4555`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(48_827_576, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			// Standard Error: 2_771
			.saturating_add(Weight::from_parts(43_971, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:0)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	fn increase_budget() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `375`
		//  Estimated: `4555`
		// Minimum execution time: 52_000_000 picoseconds.
		Weight::from_parts(52_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:0)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn decrease_budget() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `375`
		//  Estimated: `4555`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn set_policy(n: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `170 + n * (32 ±0)`
		//  Estimated: `4555`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_449_594, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			// Standard Error: 1_900
			.saturating_add(Weight::from_parts(43_346, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	fn pause() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `4555`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	fn resume() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `4555`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn unregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `376`
		//  Estimated: `4555`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn register_sponsor(n: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `4555`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(48_827_576, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			// Standard Error: 2_771
			.saturating_add(Weight::from_parts(43_971, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:0)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	fn increase_budget() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `375`
		//  Estimated: `4555`
		// Minimum execution time: 52_000_000 picoseconds.
		Weight::from_parts(52_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:0)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn decrease_budget() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `375`
		//  Estimated: `4555`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn set_policy(n: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `170 + n * (32 ±0)`
		//  Estimated: `4555`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_449_594, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			// Standard Error: 1_900
			.saturating_add(Weight::from_parts(43_346, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	fn pause() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `4555`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	fn resume() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `4555`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: `SponsoredTx::Sponsors` (r:1 w:1)
	/// Proof: `SponsoredTx::Sponsors` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn unregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `376`
		//  Estimated: `4555`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(46_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4555))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
