import { createClient, PolkadotClient, TypedApi } from "polkadot-api";
import { getWsProvider } from "polkadot-api/ws-provider/web";
import { getPolkadotSigner } from "polkadot-api/signer";
import { sr25519CreateDerive } from "@polkadot-labs/hdkd";
import {
  DEV_PHRASE,
  entropyToMiniSecret,
  mnemonicToEntropy,
} from "@polkadot-labs/hdkd-helpers";
// @ts-ignore — generated by `npx papi add`
import { sponsored } from "@polkadot-api/descriptors";

const WS_URL = "ws://127.0.0.1:9944";

// Derive dev account keypairs from the well-known dev mnemonic.
const miniSecret = entropyToMiniSecret(mnemonicToEntropy(DEV_PHRASE));
const derive = sr25519CreateDerive(miniSecret);

export const alice = getPolkadotSigner(
  derive("//Alice").publicKey,
  "Sr25519",
  derive("//Alice").sign,
);

export const bob = getPolkadotSigner(
  derive("//Bob").publicKey,
  "Sr25519",
  derive("//Bob").sign,
);

export const charlie = getPolkadotSigner(
  derive("//Charlie").publicKey,
  "Sr25519",
  derive("//Charlie").sign,
);

// SS58-encoded addresses for display and storage queries.
export const aliceAddress = "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY";
export const bobAddress = "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty";
export const charlieAddress = "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y";

let client: PolkadotClient | null = null;
let api: TypedApi<typeof sponsored> | null = null;

export async function connect(): Promise<TypedApi<typeof sponsored>> {
  client = createClient(getWsProvider(WS_URL));
  api = client.getTypedApi(sponsored);
  return api;
}

export function getApi(): TypedApi<typeof sponsored> {
  if (!api) throw new Error("Not connected");
  return api;
}

export function disconnect() {
  client?.destroy();
  client = null;
  api = null;
}
